blank_issues_enabled: false
contact_links:
  - name: Milex Community Support
    url: https://forum.milex.org/c/support
    about: Please ask and answer support questions here.
  - name: Milex Feature Requests
    url: https://forum.milex.org/c/ideas
    about: We use GitHub issues as a bug tracker only. Please go to https://forum.milex.org/c/ideas to find support and discuss features/ideas.
