<?php

return [
    'name'        => 'CRM',
    'description' => 'Enables integration with Milex supported CRMs.',
    'version'     => '1.0',
    'author'      => 'Milex',
    'routes'      => [
        'public' => [
            'milex_integration_contacts' => [
                'path'         => '/plugin/{integration}/contact_data',
                'controller'   => 'MilexCrmBundle:Public:contactData',
                'requirements' => [
                    'integration' => '.+',
                ],
            ],
            'milex_integration_companies' => [
                'path'         => '/plugin/{integration}/company_data',
                'controller'   => 'MilexCrmBundle:Public:companyData',
                'requirements' => [
                    'integration' => '.+',
                ],
            ],
            'milex_integration.pipedrive.webhook' => [
                'path'       => '/plugin/pipedrive/webhook',
                'controller' => 'MilexCrmBundle:Pipedrive:webhook',
                'method'     => 'POST',
            ],
        ],
    ],
    'services' => [
        'events' => [
            'milex_integration.pipedrive.lead.subscriber' => [
                'class'     => \MilexPlugin\MilexCrmBundle\EventListener\LeadSubscriber::class,
                'arguments' => [
                    'milex.helper.integration',
                    'milex_integration.pipedrive.export.lead',
                ],
            ],
            'milex_integration.pipedrive.company.subscriber' => [
                'class'     => \MilexPlugin\MilexCrmBundle\EventListener\CompanySubscriber::class,
                'arguments' => [
                    'milex.helper.integration',
                    'milex_integration.pipedrive.export.company',
                ],
            ],
            'milex.integration.leadbundle.subscriber' => [
                'class'     => \MilexPlugin\MilexCrmBundle\EventListener\LeadListSubscriber::class,
                'arguments' => [
                    'milex.helper.integration',
                    'milex.lead.model.list',
                    'translator',
                ],
            ],
        ],
        'integrations' => [
            'milex.integration.hubspot' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\HubspotIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                    'milex.helper.user',
                ],
            ],
            'milex.integration.salesforce' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\SalesforceIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                ],
            ],
            'milex.integration.sugarcrm' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\SugarcrmIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                    'milex.user.model.user',
                ],
            ],
            'milex.integration.vtiger' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\VtigerIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                ],
            ],
            'milex.integration.zoho' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\ZohoIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                ],
            ],
            'milex.integration.dynamics' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\DynamicsIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                ],
            ],
            'milex.integration.connectwise' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\ConnectwiseIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                ],
            ],
            'milex.integration.pipedrive' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\PipedriveIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'milex.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'session',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.milex',
                    'milex.helper.encryption',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                    'milex.helper.paths',
                    'milex.core.model.notification',
                    'milex.lead.model.field',
                    'milex.plugin.model.integration_entity',
                    'milex.lead.model.dnc',
                    'milex_integration.service.transport',
                    'milex_integration.pipedrive.export.lead',
                ],
            ],
        ],
        'other' => [
            'milex_integration.pipedrive.guzzle.client' => [
                'class' => 'GuzzleHttp\Client',
            ],
            'milex_integration.service.transport' => [
                'class'     => 'MilexPlugin\MilexCrmBundle\Services\Transport',
                'arguments' => [
                    'milex_integration.pipedrive.guzzle.client',
                ],
            ],
            'milex_integration.pipedrive.import.owner' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\Pipedrive\Import\OwnerImport::class,
                'arguments' => [
                    'doctrine.orm.entity_manager',
                ],
            ],
            'milex_integration.pipedrive.import.company' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\Pipedrive\Import\CompanyImport::class,
                'arguments' => [
                    'doctrine.orm.entity_manager',
                    'milex.lead.model.company',
                ],
            ],
            'milex_integration.pipedrive.import.lead' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\Pipedrive\Import\LeadImport::class,
                'arguments' => [
                    'doctrine.orm.entity_manager',
                    'milex.lead.model.lead',
                    'milex.lead.model.company',
                ],
            ],
            'milex_integration.pipedrive.export.company' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\Pipedrive\Export\CompanyExport::class,
                'arguments' => [
                    'doctrine.orm.entity_manager',
                ],
            ],
            'milex_integration.pipedrive.export.lead' => [
                'class'     => \MilexPlugin\MilexCrmBundle\Integration\Pipedrive\Export\LeadExport::class,
                'arguments' => [
                    'doctrine.orm.entity_manager',
                    'milex_integration.pipedrive.export.company',
                ],
            ],
        ],
        'forms' => [
            'milex.form.type.connectwise.campaignaction' => [
                'class'     => MilexPlugin\MilexCrmBundle\Form\Type\IntegrationCampaignsTaskType::class,
                'arguments' => ['milex.integration.connectwise'],
            ],
        ],
        'commands' => [
            'milex_integration.pipedrive.data_fetch' => [
                'tag'       => 'console.command',
                'class'     => MilexPlugin\MilexCrmBundle\Command\FetchPipedriveDataCommand::class,
                'arguments' => [
                    'milex.helper.integration',
                    'templating.helper.translator',
                ],
            ],
            'milex_integration.pipedrive.data_push' => [
                'tag'       => 'console.command',
                'class'     => MilexPlugin\MilexCrmBundle\Command\PushDataToPipedriveCommand::class,
                'arguments' => [
                    'milex.helper.integration',
                    'templating.helper.translator',
                    'doctrine.orm.entity_manager',
                    'milex_integration.pipedrive.export.company',
                    'milex_integration.pipedrive.export.lead',
                ],
            ],
        ],
    ],
];
